apiVersion: dws.cray.hpe.com/v1alpha2
kind: Workflow
metadata:
  name: base
spec:
  # Add fields here
  desiredState: Proposal
  dwDirectives:
    - "#DW Proposal action=complete"

    # By specifying "error", the driver will cause the step to fail.
    # Note that underscores are used in the error message to represent
    # spaces; the controller will swap them back when it records the error.
    #- "#DW Proposal action=error message=deans_error severity=Major"

    # An error will also have a severity.  The severity is ignored for all
    # other actions.

        # The severity must be one of the following recognized by
        # DWS: Minor, Major, Fatal.
        #
        # An unspecified severity will be a Minor severity.
        #
        # A severity of Minor is a condition that the driver developer believes
        # will eventually succeed, and the driver is left in DriverWait state.
        # This could be an IsConflict() condition, for example.
        #
        # A severity of Major is a transient error and the driver developer
        # is not certain that it will eventually succeed, and the driver is
        # left in a TransitentCondition state.  These could be persistent due
        # to an underlying problem, such as errors from OS calls.
        #
        # A severity of Fatal is an indication to the WLM that it should not
        # expect this job to proceed and it should clean up the job.
        # This could be due to an invalid DW directive.

    # By specifying "wait", the driver will leave the state in DriverWait,
    # and a test tool will transition this to "complete".
    # The test tool acts as an extension of dws-test-driver.
    #- "#DW Proposal action=wait"

  wlmID: "TD WLM"
  jobID: "TD Job 26"
  userID: 1001
  groupID: 1001


