apiVersion: dws.cray.hpe.com/v1alpha2
kind: Workflow
metadata:
  name: complex
spec:
  # Add fields here
  desiredState: Proposal
  dwDirectives:

    # Use this with the config/samples/run-complex.sh script.

    # This workflow will proceed through Proposal state and on to Setup state
    # where it will remain with a status of DriverWait until a
    # test tool moves that state to Complete.  Then this workflow will proceed
    # to DataIn state where it will end with an error.

    - "#DW Setup action=wait"

    # Note that underscores are used in the error message to represent
    # spaces; the controller will swap them back when it records the error.
    - "#DW DataIn action=error message=sample_data_error severity=Fatal"

  wlmID: "TD WLM"
  jobID: "TD Job 27"
  userID: 1001
  groupID: 1001


